apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  project: default
  source:
    repoURL: https://github.com/michaelkedey/example-voting-app.git
    targetRevision: main
    path: k8s-specifications/vote-app
  destination:
    server: https://kubernetes.default.svc
    namespace: vote-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true