apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dull-teams-hang.loca.lt
      http:
        paths:
          - path: /db
            pathType: Prefix
            backend:
              service:
                name: db-service
                port:
                  number: 5432
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: redis-service
                port:
                  number: 6379
          - path: /result
            pathType: Prefix
            backend:
              service:
                name: result-service
                port:
                  number: 5001
          - path: /vote
            pathType: Prefix
            backend:
              service:
                name: vote-service
                port:
                  number: 5000
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 8080